version: '3'
services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    depends_on:
      - operacoes
    command: python calculadora.py
    volumes:
      - ./tests:/app/tests
    environment:
      - PYTHONUNBUFFERED=1

  operacoes:
    build:
      context: .
      dockerfile: Dockerfile-operacoes
    ports:
      - "50000:50000"
